name: DigitalOcean App Platform deployment
description: Publish a Docker image to DigitalOcean's App Platform
branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  app_name:
    description: name of the app image
    required: true
  list_of_image:
    description: list of json object containing name, repository and tag of the digitalocean container registry to update
    required: true

runs:
  using: composite
  steps:
    - name: Install command_line dependencies
      shell: bash
      run: apk add -U curl git jq && \
            wget -q -O /usr/bin/yq $(wget -q -O - https://api.github.com/repos/mikefarah/yq/releases/44514558 | jq -r '.assets[] | select(.name == "yq_linux_amd64") | .browser_download_url') && \
            chmod +x /usr/bin/yq && \
            
    - name: Update image on App Platform
      shell: bash
      run: ./fo.sh